### DISCUSSION TITLE
Where are the CI bench results published?

### DISCUSSION THREAD

**Discussion by denosaurtrain** [hyperium/hyper#3497] [Q&A] [answered]
CI is running benchmarks automatically (e.g., see the [GitHub Actions job for hyper v1.1.0](https://github.com/hyperium/hyper/actions/runs/7249783197/job/19748519103)), but I'm having a hard time finding the results.

The CI workflow [.github/workflows/bench.yml](https://github.com/hyperium/hyper/blob/master/.github/workflows/bench.yml) references the action `seanmonstar/github-action-benchmark`:

```yaml
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: seanmonstar/github-action-benchmark@v1-patch-1
        with:
          name: ${{ matrix.bench }}
          # What benchmark tool the output.txt came from
          tool: 'cargo'
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          # # Where the previous data file is stored
          # external-data-json-path: ./cache/benchmark-data.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          #alert-comment-cc-users: '@seanmonstar'
          auto-push: true
```

The README for [seanmonstar/github-action-benchmark](https://github.com/seanmonstar/github-action-benchmark) says that the results are available on https://rhysd.github.io/github-action-benchmark/dev/bench/, but that's a 404. Presumably that URL is left over from the fork of [benchmark-action/github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark). In trying to find the correct URL, I note that the branch `v1-patch-1` has no README, and when I [compare `v1-patch-1` to `master`](https://github.com/seanmonstar/github-action-benchmark/compare/master...seanmonstar:github-action-benchmark:v1-patch-1), GitHub says:

> There isn’t anything to compare.
> master and v1-patch-1 are entirely different commit histories.

Guessing based on [one line of the CI job logs](https://github.com/hyperium/hyper/actions/runs/7249783197/job/19748519103#step:6:168), I speculate that the results are stored in the `gh-pages` branch of the `hyperium/hyper` repo. However, [the GitHub Pages deployment](https://github.com/hyperium/hyper/deployments/github-pages) points to https://hyper.rs/hyper, which is a 404.
