### ISSUE TITLE
Hello, World doesn't work!

### ISSUE THREAD

**Issue by bxqgit** [hyperium/hyper#1230]
I'm trying to run Hello, World example from the front page of the project and it won't work. There's no Cargo.toml content to run the example. I tried using this configuration, but it still doesn't work:

```
[dependencies]
hyper = "0.11"
service_fn = "0.1.0"

[dev-dependencies]
service-fn = { git = "https://github.com/tokio-rs/service-fn" }
```

The compiler gives **E0463** for **service-fn** dependency.

**Comment by seanmonstar** [comment]
I'm not sure what that error is, could you include it? All the code blocks in the documentation are compiled, so I do know it can work. Looking at your pasted TOML, I'd suggest this tweak:

```toml
[dependencies]
hyper = "0.11"
service-fn = { git = "https://github.com/tokio-rs/service-fn" }
```
