### ISSUE TITLE
Set the in-git crate version to the latest release version to unblock cargo patches

### ISSUE THREAD

**Issue by MOZGIII** [hyperium/hyper#2362]
We'd like to lock to the git version if possible, and use the latest commit https://github.com/hyperium/hyper/commit/1dd761c87de226261599ff2518fe9d231ba1c82d from there. Currently, we can't do it via cargo,'s patch mechanism due to the difference in versions.

Is this intentional?

If not - please set the in-git-tree crate version to something 0.13-ish so it's possible to use the following annotation at `Cargo.toml`:

```toml
[patch.crates-io]
hyper = { version = "0.14.0-dev", git = "https://github.com/hyperium/hyper", rev = "21dea2114574bbeda41bad5dff5e8e3613352124" }
```
