### ISSUE TITLE
hyper-util: `ReadVersion` misses magic bytes when connecting with latest version of Firefox

### ISSUE THREAD

**Issue by lennartkloock** [hyperium/hyper#3841]
**Version**
```toml
hyper = { version = "1.5.2", features = ["http1", "http2", "server", "tracing"] }
hyper-util = { version = "0.1.10", features = ["server-auto", "tokio"] }
```

**Platform**
`Linux 6.12.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.6-1 (2024-12-21) x86_64 GNU/Linux`

**Description**
When using Firefox `134.0.2` to request a simple service that was set up with `auto::Builder::serve_connection` some HTTP/2 connections get stuck.
It seems to be related to the `poll` function of the `ReadVersion` struct. This is also confirmed by the fact that the problem disappears when I set the `Builder` to `http2_only`.
It seems to be waiting for more data from the client (on this line https://github.com/hyperium/hyper-util/blob/master/src/server/conn/auto/mod.rs#L275) and the connection eventually errors with `Err(hyper::Error(Parse(Method)))` because Firefox sends a `PING` frame.
It doesn't seem to be a problem when using Chrome.
