### ISSUE TITLE
Performance of hyper-v1 as the api-gateway

### ISSUE THREAD

**Issue by lsk569937453** [hyperium/hyper#3895]
I just test the performace of hyper-v1 as the api-gateway.I've noticed its performance is extremely poor. When accessing the backend API directly, the TPS reaches 200,000. When accessing through Nginx, the TPS is around 150,000. However, when accessing the backend API through my hyper-gateway, the TPS drops to less than 100,000.

# Hyper Gateway Source Code
```
use clap::Parser;
use hyper::{server::conn::http1, service::service_fn};
use hyper_util::client::legacy::Client;
use hyper_util::client::legacy::connect::HttpConnector;
use hyper_util::rt::TokioIo;
use std::net::SocketAddr;
use tokio::net::TcpListener;
#[derive(Parser, Debug, Clone)]
#[command(version = "1.0", long_about = None) ]
pub struct Cli {
    /// The config file path
    #[arg(short = 'f', long, default_value = "0.0.0.0:8090")]
    pub out_addr: String,
}
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    println!("cli: {:?}", cli);

    let in_addr: SocketAddr = ([0, 0, 0, 0], 8084).into();

    let client_main =
        Client::builder(hyper_util::rt::TokioExecutor::new()).build(HttpConnector::new());

    let listener = TcpListener::bind(in_addr).await?;

    println!("Listening on http://{}", in_addr);
    println!("Proxying on http://{}", cli.out_addr);

    loop {
        let out_addr_clone = cli.out_addr.clone();
        let (stream, _) = listener.accept().await?;
        let io = TokioIo::new(stream);

        let client = client_main.clone();
        let service = service_fn(move |mut req| {
            let client = client.clone();

            let uri_string = format!(
                "http://{}{}",
                out_addr_clone,
                req.uri()
                    .path_and_query()
                    .map(|x| x.as_str())
                    .unwrap_or("/")
            );
            let uri = uri_string.parse().unwrap();
            *req.uri_mut() = uri;

            async move { client.request(req).await }
        });

        tokio::task::spawn(async move {
            if let Err(err) = http1::Builder::new().serve_connection(io, service).await {
                println!("Failed to serve connection: {:?}", err);
            }
        });
    }
}

```
```
[dependencies]
hyper={version = "1.6.0",features = ["full"]}
tokio={version = "1.45.1",features = ["full"]}
hyper-util = { version = "0.1.12", features = ["full"] }
clap = { version = "4.5.38", features = ["derive"] }
```

# The docker-compose.yaml for testing
```
version: "3.9"

services:
  test:
    image: demisto/rakyll-hey:1.0.0.44140
    container_name: hey
    tty: true
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 8192M
  backend:
    image: ghcr.io/lsk569937453/echo-server:0.0.5
    container_name: backend
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M
  hyper-test:
    image: lsk569937453/hyper-test:0.0.1
    container_name: hyper
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M

```
I conducted tests using Docker. The testing tool is hey, launched via the above docker-compose.yaml, then entered the hey container to execute these TPS test commands:
- Direct request to backend API:
```
hey -n 100000 -c 250 -m GET http://backend:80/
```
- Request through gateway:
```
hey -n 100000 -c 250 -m GET http://hyper:8084
```
