### ISSUE TITLE
please remove 'openssl' ...

### ISSUE THREAD

**Issue by fhbzyc** [hyperium/hyper#785]
build in windows too many error...

**Comment by seanmonstar** [comment]
I recognize openssl has some annoyances on Windows. Work is happening, and soon hyper will use `native-tls` by default instead, which should only require openssl on Linux OSes.

For now, you can disable openssl by doing this in your `Cargo.toml`:

```toml
[dependencies.hyper]
version = "0.9"
default-features = false
```
